version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes: 
      - es01:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5  
    networks: 
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    volumes: 
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro   
    container_name: kibana
    ports: ['5601:5601']
    networks: 
        - stack
    depends_on: 
        - elasticsearch
    healthcheck:
        test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
        interval: 30s
        timeout: 10s
        retries: 5
    command:
        - bash
        - -c 
        - |
          set -e
          set -x

          until curl -s http://elasticsearch:9200 ; do
            >&2 echo "Elastic is unavailable - sleeping"
            sleep 1
          done

          >&2 echo "Elastic is up"

          echo "Starting Kibana"
          /opt/kibana/bin/kibana

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.0
    container_name: apm_server
    ports: ['8200:8200']
    networks: ['stack']
    volumes:
      - './apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro'
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: curl -s https://localhost:8200/healthcheck >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - bash
      - -c 
      - |
        set -e
        set -x

        until (curl -s http://elasticsearch:9200 && curl -s http://kibana:5601/app/apm); do
          >&2 echo "Elastic and Kibana are unavailable - sleeping"
          sleep 1
        done

        >&2 echo "They are up"

        echo "Starting APM-SERVER"
        apm-server --strict.perms=false setup -e ; apm-server --strict.perms=false -e      
networks: 
  stack:
    driver: bridge

volumes:
  es01:
    driver: local